### ISSUE TITLE
Elassandra support?

### ISSUE THREAD

**Issue by thelordoftheboards** [masumsoft/express-cassandra#119]
I noticed in the comments that Elassandra is mentioned. Any plans on `official` support?

**Comment by masumsoft** [comment]
@thelordoftheboards As #118 was merged recently, so it won't hurt anymore if you are using elassandra. I'm not quite sure yet how much work needs to be done to support it officially. We already have some sort of support for solr (the default choice for datastax enterprise), but as elassandra is becoming a real thing, we would definitely consider it.

Our team was using `cassandra-lucene-index` so far in production and though it's a great open source project, we were considering to move to `datastax enterprise` due to several limitations of it. If elassandra proves to be a good alternative to datastax enterprise for us, then we would have it officially supported in express-cassandra. Otherwise we would always welcome community contributions for it and appreciate any merge requests to support it.

**Comment by thelordoftheboards** [comment]
@masumsoft This is awesome - thank you so much. I currently have a SaaS that uses both Cassandra and Elastic Search separately, and express-cassandra is the solution of accessing the Cassandra part (through GraphQL and DataLoader). Been evaluating Elassandra as a two-in-one package to have both. Happy to see that you are making it easy to support it, and if there is some reasonable improvement we can make I'll be glad to PR.

**Comment by masumsoft** [comment]
Elassandra support is available in v2.0.0

http://express-cassandra.readthedocs.io/en/stable/elassandra/
