### ISSUE TITLE
LGPLv3 License question - not an issue

### ISSUE THREAD

**Issue by 0v3rst33r** [masumsoft/express-cassandra#134]
Sorry for creating issue here, but didn't know where else to collaborate about this:  I just wanted to know why `LGPLv3` is being used for this project?

**Comment by masumsoft** [comment]
I initially thought to use an MIT license, but express-cassandra started off from a highly modified version of [apollo-cassandra](https://github.com/3logic/apollo-cassandra) module and that module was licensed under LGPLv3 which requires you to open source the distribution of the modified version of it with the same license and terms.

Note that users of this module don't fall under this restriction and they can use it as an npm module without open sourcing their codebase. The open sourcing conditions apply only if you want to change/improve the source code and redistribute it.

Though recently major refactoring and new development went on to support missing features of cassandra 3.x and additional functionalities and the original module codebase of apollo-cassandra is  no longer there. 

If the license restricts you from doing something you would have done otherwise with a more open license, please let me know, so I can reconsider the license terms.
