### ISSUE TITLE
i cant find the documentation about migration

### ISSUE THREAD

**Issue by arnaz06** [masumsoft/express-cassandra#157]

**Comment by vgjenks** [comment]
Yes - migrations seems to be completely undocumented. No idea how to use it. Please help.

**Comment by masumsoft** [comment]
Migration is an experimental feature and kind of automatic at this moment. You just set the [migration behaviour](http://express-cassandra.readthedocs.io/en/stable/usage/#explanations-for-the-options-used-to-initialize) in the configuration and express-cassandra tries to do the rest for you. As cassandra is more restrictive compared to popular sql databases in terms of schema modifications, so it's difficult to implement a full fledged migration system as supported by popular SQL ORMs.

Express cassandra currently does automatic migration based on the differences between the current database schema and the  schema defined in the code. It migrates the database automatically when it's "safe" and "possible" to do so. Otherwise it throws an error and requires manual migration by the developer.
