### ISSUE TITLE
options: createdAt and updatedAt both updated when saving/updating existing record

### ISSUE THREAD

**Issue by vgjenks** [masumsoft/express-cassandra#172]
In reference to the "timestamps" option: https://express-cassandra.readthedocs.io/en/stable/schema/

When using .save() on an existing record, the record is updated (not inserted) but the createdAt timestamp is updated. Would expect only the updatedAt value to change in this scenario.

I have not tried using .update() but would prefer to use .save() and the if_exists: true flag, as we have been.

Pretty straightforward but will provide code samples if need be.

Thanks!

**Comment by masumsoft** [comment]
@vgjenks are you creating the record as a new object or using find -> modify -> save?

When you create a new object the ORM treats it as a new record and hence sets the createdAt. When creating a new object, the ORM does not check whether an entry with the same primary key exists in db. This is intentional because this type of scenarios could be handled using light weight transactions and express-cassandra let the user decide what to do here.

So you could either use the .update() with if_exists: true or use find -> modify -> save.
