### ISSUE TITLE
DropTableSchemaOnChange

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#22]
Hi! I wanted to know if we set this option to true in ormOptions do we lose the data in the table every time there is a change in the schema??

**Comment by masumsoft** [comment]
For now, the answer is unfortunately yes. I would recommend setting this to false in production. It's there for ease of development when you change the schema, the table should sync automatically with your model schema and to do that right now the ORM just drops the table and recreates it. 

Migrations support is on it's roadmap, though there is no simple and effective solution to this problem at this moment. But will be working on it asap, because at my company we also require that feature to be there.

**Comment by vamzz1** [comment]
Okay. Thanks for the info man. Hope you guys do it soon. Also can you suggest a work around for this if there's any.

**Comment by masumsoft** [comment]
You may for now use cqlsh to export your data using the COPY TO command and after the schema change, import that data into the updated table using the COPY FROM command. You can get more details on it here: https://docs.datastax.com/en/cql/3.3/cql/cql_reference/copy_r.html
