### ISSUE TITLE
Support for importing fixture data and migrations on schema changes

### ISSUE THREAD

**Issue by masumsoft** [masumsoft/express-cassandra#27]
Data migrations on schema change instead of dropping and recreating the tables is an awaited feature. Also when only indexes, materialized views, custom indexes etc are changed, only recreate those instead of dropping the whole table.

**Comment by masumsoft** [comment]
Reference doc for migration: https://docs.datastax.com/en/cql/3.3/cql/cql_reference/copy_r.html

**Comment by ssuperczynski** [comment]
Hey @masumsoft we have been thinking to add our own migration command. Have you started this issue? We can help you

**Comment by masumsoft** [comment]
@ssuperczynski Nope, I didn't get much time to start implementing this yet, but had plans to start soon. It's really nice to know that you guys are interested to contribute. Let's move on, hopefully I'll be joining soon.

**Comment by masumsoft** [comment]
My plan for now is to take a conservative approach on it as listed below, please let me know if anyone have any suggestions:

Migrations
------------
1. When a new field is added, it will alter the table to add that field.
2. When a field is removed, it will alter the table to drop that field.
3. When a field type/typeDef is changed, if the new type is compatible to the old type according to [this table](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cql_data_types_c.html?scroll=ref-cql-data-types__cql_data_type_compatibility) then the type will be altered and the data will remain intact, otherwise the table will be altered to drop the field and add the field with the new type/typeDef.  
4. When a field is renamed, then a special attribute, something like `old_field_name` should be given in the field definition, so that the rename can be detected and the table can be altered accordingly keeping the data intact.
5. When indexes, materialized views or custom indexes are added/removed, only they will be created/dropped and the original table and data will be kept intact. 
6. When an existing materialized view structure is changed, alter the materialized view.
7. When an existing custom index structure is changed, drop and recreate the custom index.
8. When an user defined type is changed, alter the type accordingly and try updating the corresponding tables and types that uses that type (It will be a bit challenging to safely alter a user defined type and I need to think about it a bit more and confirm with the cassandra docs about the feasibility).

Fixtures
----------
1. Fixture data can be loaded from a pre occupied csv file and the file location can either be configurable in the schema by introducing an additional attribute something like `fixture_file` or keeping a global directory named `fixtures` where each table will have a csv file with the corresponding table name.
2. Fixture data can be loaded by emulating the cassandra builtin COPY command or using a csv parser to read the data and then nodejs-driver batch inserts.
3. Fixtures should only be loaded on empty tables and can be disabled in config for production. Or it can be a separate function call, so that the developer can decide when to load the fixtures.

**Comment by thelordoftheboards** [comment]
This is a very thorough and well thought out plan.

I would like to comment that everything in Migrations except 4 (renaming a field) would essentially be completely automatic. In order to ensure correctness the best way is indeed to require specifying `old_field_name`. There are of course limitations when dealing with multiple versions where one field would be renamed multiple times, for instance 'fieldA' to 'fieldB' and then 'fieldB' to 'fieldC'. The migration would fail if the database still contains 'fieldA'. However, this is a purely theoretical situation which would be easily preventable with proper change management.

If possible, I would like to be able to control the migration behavior through a separate function call, like mentioned in Fixtures 3, but for migrations. The use case for that would be a web server farm with multiple load balanced node.js servers running the application which contains the models. In certain scenarios it would be best to have only one of them perform the migration.

**Comment by thelordoftheboards** [comment]
"When a primary key structure is changed cassandra won't allow altering the primary key and it doesn't seem to support renaming a table name. ..... Should we rather drop and recreate in case of primary key changes or be brave and say lets do it?)"

If drop and re-create is the only option, I would like to be able to forbid its use, globally. My preference would be the schema loading to fail, and to have to apply a CQL script that does the migration, rather than wiping out table with potentially irreplaceable data in production.

In general, when it comes to the migration, my preference would be to always fail hard, instead of taking a dubious course of action, and at no point in time allow the destruction of data.

While being able to re-create tables for some test instance is a great convenience, running even the slightest chance of deleting production data should be a no no.

**Comment by masumsoft** [comment]
@thelordoftheboards You are right. Btw, I thought we should allow any destructive operation only when the `dropTableOnSchemaChange` is set to true and it is recommended to set to false in production which is documented. We could also check the env and disallow if the app is running in production mode. Also to remain safe even in dev mode, we could ask the user for confirmation whether to drop the table or not. What do you think?

**Comment by thelordoftheboards** [comment]
I like the idea about using `dropTableOnSchemaChange` - this pretty much acts as a guardian against accidental deletion.
The asking is a good idea also - can't go wrong with that!
As for the .env, I do like that too. However, I would like to point out that sometimes .env is set to true even during testing, just to make sure things work well.
Overall, I think if asking the user is possible to implement, it is a great catch all. The answer to the question could even be to type the table name, like when github asks for confirmation for deleting a repository. I think it is totally worth the overhead.

**Comment by masumsoft** [comment]
fixtures are coming soon in v2.0.0

**Comment by masumsoft** [comment]
Fixtures are available in v2.0.0

http://express-cassandra.readthedocs.io/en/stable/usage/#exportimport-fixture-data
