### ISSUE TITLE
Question: Is it possible to add "toJSON" method for "BaseModel"?

### ISSUE THREAD

**Issue by littledesu** [masumsoft/express-cassandra#53]
e.g. if I return model to client I see object like this:
```js
Object {
  _validators: Object
  id:"473198a5-e3c9-4f70-ae0b-a4e9b6b64284"
  name:"name"
  __proto__:Object
}
```
but I want something like this:
```json
{
  "id": "473198a5-e3c9-4f70-ae0b-a4e9b6b64284",
  "name": "name"
}
```
so is it possible to add method that provides easy way to do this? I can make PR for it.

**Comment by masumsoft** [comment]
You could use the query options object parameter `{raw: true}` to get the raw object instead of a model instance. The doc describes more about it [here](https://github.com/masumsoft/express-cassandra/blob/master/README.md#find-results-are-raw-objects)

Btw, if you want a convenience method like you mentioned, I would encourage a PR for that.

**Comment by littledesu** [comment]
I think that "toJSON" method will be useful for JSON.stringify. I can make PR with one of next behaviors:
- just delete "_validations" property (faster)
- use constructor._properties.schema (more reliable)
