### ISSUE TITLE
Unable to do range quesry on timestamp

### ISSUE THREAD

**Issue by ssuperczynski** [masumsoft/express-cassandra#57]
Given I have this query:

```js
    const query = {
      brand_name: 'Test21',
      created: { '$gt': '2016-06-06' },
    };
    UserLike.find(query, {select: ['created']}, (err, likes) => {
      if (err) reject(err);
      console.log("likes: ", likes);
    })
```

where`created` is a `timestamp` in Cassandra, I am unable to get **greather than** values.
In the console I am getting `likes: undefined`

Is it possible to get range between two dates in this library. I can't find it in documentation

**Comment by ssuperczynski** [comment]
Apologise, didn't have index set on `created` column

**Comment by masumsoft** [comment]
The doc contains an example of a range query [here](https://github.com/masumsoft/express-cassandra#find-a-more-complex-query). You could do something like the following:

```
const query = {
      brand_name: 'Test21',
      created: { '$gt': '2016-06-06', '$lte': '2016-06-08' },
};
```

The above is assuming the `created` field to be of type `text` or `varchar`. If they are of type `Date` for example, then you might need to provide proper typed values here like the following:

```
const query = {
      brand_name: 'Test21',
      created: { '$gt': new Date('2016-06-06'), '$lte': new Date('2016-06-08') },
};
```

Proper type conversion is very important in some cases, because for some cassandra types there are no native javascript types that is compatible. In those cases you might need to use the custom data types provided here as reference: https://github.com/masumsoft/express-cassandra#cassandra-to-javascript-datatypes
