### ISSUE TITLE
BigInt type not accepting Number

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#62]
I am currently using express-cassandrav0.8.0, when i updated to the latest version a column in my table having "bigint" as its type is complaining with apollo.model.value.invalidvalue: Invalid Value: "1470212053748" for Field: sessionId (Type: bigint). And the variable's type i was using to update the column "sessionId" is Number. I am really stuck here why its not accepting Number for the "bigint" field.

**Comment by masumsoft** [comment]
The validation system has been upgraded to properly handle datatypes in >= v1.0. So You now need to create a proper `Long` datatype for `bigint`. Instead of directly passing a string "1470212053748", you now need to convert your numeric string to the `Long` datatype by using something like `models.datatypes.Long.fromString("1470212053748");`

The Javascript to Cassandra type conversions are documented [here](https://github.com/masumsoft/express-cassandra#cassandra-to-javascript-datatypes).

**Comment by vamzz1** [comment]
Thanks for the solution.
