### ISSUE TITLE
doBatch issue

### ISSUE THREAD

**Issue by szavrakas** [masumsoft/express-cassandra#80]
I am trying to use the doBatch that it is documented here:
http://express-cassandra.readthedocs.io/en/latest/batch/

As I see [here](https://github.com/masumsoft/express-cassandra/blob/master/src/expressCassandra.js#L128) the doBatch is defined in the prototype of the function and [here](https://github.com/masumsoft/express-cassandra/blob/master/src/expressCassandra.js#158) the doBatch is defined as property of the CassandraClient function and finally this function is proxying the call to the prototype function by checking the number of parameters as well.

In my case, following the documentation and calling the doBatch it is calling the doBatch in the prototype directly. Also I am able to see the doBatch only as part of the prototype in the debugger. Did I do something  wrong or is it possible that somewhere the doBatch that is part of the function is dropped?

**Comment by masumsoft** [comment]
If I understood your concern correctly, this is happening because you can initialise express-cassandra in two distinct ways. You could either [load models from a defined directory](http://express-cassandra.readthedocs.io/en/latest/usage/#auto-load-models-from-a-directory) or you can [load and organise models yourself](http://express-cassandra.readthedocs.io/en/latest/usage/#alternatively-load-organize-models-yourself).

When you load and organise models yourself, I guess you are using the `createClient` to initialise your models instance and then trying to use models.doBatch from that instance. So in this case only the prototype function will be available to the instance object. Following is an example:

```js
var expressCassandra = require('express-cassandra');
var models = expressCassandra.createClient({
    // ...
});

// models.doBatch is the prototype function
// expressCassandra.doBatch is the function containing the checks for the number of params
```

models.doBatch would be appropriate you were using the auto load models from directory system to initialise your models like the following:

```
var models = require('express-cassandra');

models.setDirectory( __dirname + '/models').bind(
    {
        //...
    },
    function(err) {
        // models.doBatch would be the function containing the checks for the number of params
    }
);
```

**Comment by szavrakas** [comment]
You understood my question correctly! Thanks for your reply :)

I am loading the models myself and not from a directory. The problem that I had was that I was passing the `queries` and the `callback` as params to the `doBatch` and it was breaking because there is no check about the number of arguments inside the `prototype.doBatch`. Instead in the `CassandraClient.doBatch`. Instead in the `prototype.doBatch` there is this check:
```
  if (arguments.length === 2) {
    callback = options;
    options = {};
  }
```

Should I add it and create a merge request? By the way, I couldn't find any documentation about the `options`. What are the possible values that I can pass there?

**Comment by masumsoft** [comment]
The options object is passed to the nodejs-driver directly. The available options can be found in the nodejs-driver docs: http://docs.datastax.com/en/developer/nodejs-driver/3.1/api/type.QueryOptions/
