### ISSUE TITLE
Operators support

### ISSUE THREAD

**Issue by sudheerj** [masumsoft/express-cassandra#87]
Currently Iam trying to migrate from mongoDB(mongoose) to Cassandra(express-cassandra) ORM but it looks like express-cassandra supports few operators only.It will be better to confirm below operators support before going to proceed.

> $in,$nin,$or,$gt,$lt,$gte,$lte,$ne etc

**Comment by masumsoft** [comment]
`$in, $gt, $lt, $gte, $lte` are already supported, others are not supported by cassandra db and there is architecturally valid reason behind for not supporting them. Btw, why did you want to come from mongodb to cassandra? Is there any specific reason behind?

**Comment by sudheerj** [comment]
Thanks Masumsoft for the response.

Due to highly scalable and distributed nature we should migrate from mongoDB to Cassandra DB.The application need to handle large volume of data considering new modules as well.

**Comment by masumsoft** [comment]
Okay. So you cannot use $nin, $or or $ne because they are terrible query choices for large volume of data. You cannot reliably scale them and thus cassandra does not support them. To fulfill your requirement, you could either design the schema differently to get the required data and query differently to achieve the same result. You could also use materialized views and in some cases secondary indexes (if you know what you are doing). If you have complex filtering and searching requirements, then you could use map reduce, solr, elasticsearch etc along with cassandra.
